### ISSUE TITLE
ShellCheck - lint for shell scripts

### ISSUE THREAD

**Issue by seberm** [fort-nix/nix-bitcoin#528]
Many shell scripts in nix-bitcoin project do not pass the shellcheck lint. I think it's good idea to at least prevent the potential globbing and word splitting.

We can integrate the changes carefully and slowly.

I would like to divide the work into these parts:

1. Fix the lint of shell scripts installed on a target machine - mainly scripts called by unit files (`ExecStart(Post|Pre)`) and scripts used in packages (`postInstall`, `buildCommand`, ...)
2. Add tests which automatically check the lint of these scripts in CI
3. Fix the lint of other shell scripts (various helper scripts in this repository). We can also add automatic shellcheck test for these scripts to CI.

The draft PR of proposed changes (points 1. and 2.) will follow. Please let me know what you think.

Refs.:
- https://www.shellcheck.net/wiki/

Thanks!

cc: @erikarvstedt 

### TODOs:
- [ ] https://github.com/NixOS/nixpkgs/pull/189836
- [ ] https://github.com/fort-nix/nix-bitcoin/pull/529
- [x] https://github.com/fort-nix/nix-bitcoin/pull/531
